<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InventoryItem;
use App\Models\InventoryCategory;
use App\Models\User;
use Carbon\Carbon;

class InventoryItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = InventoryCategory::all()->keyBy('slug');
        $adminUser = User::where('role', 'admin')->first();
        $userId = $adminUser?->id;

        $items = [
            // Vaccines
            [
                'item_code' => 'VAC-001',
                'category' => 'vaccines',
                'name' => 'Canine 5-in-1 Vaccine (DHPP)',
                'brand' => 'Nobivac',
                'batch_number' => 'NV2025-001',
                'current_stock' => 50,
                'min_stock' => 10,
                'max_stock' => 100,
                'unit_price' => 850.00,
                'expiry_date' => Carbon::now()->addMonths(12),
                'supplier' => 'VetPharm Inc.',
                'location' => 'Cold Storage A1',
                'description' => 'Distemper, Hepatitis, Parvovirus, Parainfluenza vaccine',
            ],
            [
                'item_code' => 'VAC-002',
                'category' => 'vaccines',
                'name' => 'Anti-Rabies Vaccine',
                'brand' => 'Rabisin',
                'batch_number' => 'RB2025-001',
                'current_stock' => 80,
                'min_stock' => 20,
                'max_stock' => 150,
                'unit_price' => 450.00,
                'expiry_date' => Carbon::now()->addMonths(18),
                'supplier' => 'VetPharm Inc.',
                'location' => 'Cold Storage A2',
                'description' => 'Rabies vaccine for dogs and cats',
            ],
            [
                'item_code' => 'VAC-003',
                'category' => 'vaccines',
                'name' => 'Feline 4-in-1 Vaccine (FVRCP)',
                'brand' => 'Felocell',
                'batch_number' => 'FC2025-001',
                'current_stock' => 40,
                'min_stock' => 10,
                'max_stock' => 80,
                'unit_price' => 750.00,
                'expiry_date' => Carbon::now()->addMonths(10),
                'supplier' => 'VetPharm Inc.',
                'location' => 'Cold Storage A1',
                'description' => 'Feline viral rhinotracheitis, calicivirus, panleukopenia vaccine',
            ],
            // Medications
            [
                'item_code' => 'MED-001',
                'category' => 'medications',
                'name' => 'Amoxicillin 250mg',
                'brand' => 'Clavamox',
                'batch_number' => 'CL2025-001',
                'current_stock' => 200,
                'min_stock' => 50,
                'max_stock' => 300,
                'unit_price' => 25.00,
                'expiry_date' => Carbon::now()->addMonths(24),
                'supplier' => 'PetMeds Philippines',
                'location' => 'Shelf B1',
                'description' => 'Antibiotic tablets for bacterial infections',
            ],
            [
                'item_code' => 'MED-002',
                'category' => 'medications',
                'name' => 'Metronidazole 500mg',
                'brand' => 'Flagyl',
                'batch_number' => 'FL2025-001',
                'current_stock' => 150,
                'min_stock' => 30,
                'max_stock' => 200,
                'unit_price' => 18.00,
                'expiry_date' => Carbon::now()->addMonths(20),
                'supplier' => 'PetMeds Philippines',
                'location' => 'Shelf B1',
                'description' => 'Antibiotic for gastrointestinal infections',
            ],
            [
                'item_code' => 'MED-003',
                'category' => 'medications',
                'name' => 'Prednisone 5mg',
                'brand' => 'Generic',
                'batch_number' => 'PR2025-001',
                'current_stock' => 300,
                'min_stock' => 100,
                'max_stock' => 500,
                'unit_price' => 12.00,
                'expiry_date' => Carbon::now()->addMonths(18),
                'supplier' => 'PetMeds Philippines',
                'location' => 'Shelf B2',
                'description' => 'Anti-inflammatory corticosteroid',
            ],
            [
                'item_code' => 'MED-004',
                'category' => 'medications',
                'name' => 'Frontline Plus (Dog)',
                'brand' => 'Frontline',
                'batch_number' => 'FL2025-002',
                'current_stock' => 60,
                'min_stock' => 15,
                'max_stock' => 100,
                'unit_price' => 650.00,
                'expiry_date' => Carbon::now()->addMonths(24),
                'supplier' => 'VetPharm Inc.',
                'location' => 'Shelf B3',
                'description' => 'Flea and tick treatment for dogs',
            ],
            [
                'item_code' => 'MED-005',
                'category' => 'medications',
                'name' => 'Heartgard Plus',
                'brand' => 'Heartgard',
                'batch_number' => 'HG2025-001',
                'current_stock' => 45,
                'min_stock' => 10,
                'max_stock' => 80,
                'unit_price' => 550.00,
                'expiry_date' => Carbon::now()->addMonths(18),
                'supplier' => 'VetPharm Inc.',
                'location' => 'Shelf B3',
                'description' => 'Heartworm prevention chewables',
            ],
            // Surgical Supplies
            [
                'item_code' => 'SUR-001',
                'category' => 'surgical-supplies',
                'name' => 'Surgical Sutures (Absorbable)',
                'brand' => 'Vicryl',
                'batch_number' => 'VS2025-001',
                'current_stock' => 100,
                'min_stock' => 25,
                'max_stock' => 150,
                'unit_price' => 180.00,
                'expiry_date' => Carbon::now()->addMonths(36),
                'supplier' => 'MedSupply Co.',
                'location' => 'Surgical Cabinet',
                'description' => 'Absorbable sutures for internal use',
            ],
            [
                'item_code' => 'SUR-002',
                'category' => 'surgical-supplies',
                'name' => 'Sterile Surgical Gloves',
                'brand' => 'Ansell',
                'batch_number' => 'AG2025-001',
                'current_stock' => 200,
                'min_stock' => 50,
                'max_stock' => 300,
                'unit_price' => 45.00,
                'expiry_date' => Carbon::now()->addMonths(24),
                'supplier' => 'MedSupply Co.',
                'location' => 'Surgical Cabinet',
                'description' => 'Sterile latex-free surgical gloves',
            ],
            // Laboratory Supplies
            [
                'item_code' => 'LAB-001',
                'category' => 'laboratory-supplies',
                'name' => 'Blood Collection Tubes',
                'brand' => 'BD Vacutainer',
                'batch_number' => 'BD2025-001',
                'current_stock' => 500,
                'min_stock' => 100,
                'max_stock' => 800,
                'unit_price' => 15.00,
                'expiry_date' => Carbon::now()->addMonths(24),
                'supplier' => 'LabEquip Inc.',
                'location' => 'Lab Storage',
                'description' => 'EDTA blood collection tubes',
            ],
            [
                'item_code' => 'LAB-002',
                'category' => 'laboratory-supplies',
                'name' => 'Fecal Test Kit',
                'brand' => 'IDEXX',
                'batch_number' => 'IX2025-001',
                'current_stock' => 75,
                'min_stock' => 20,
                'max_stock' => 100,
                'unit_price' => 120.00,
                'expiry_date' => Carbon::now()->addMonths(12),
                'supplier' => 'LabEquip Inc.',
                'location' => 'Lab Storage',
                'description' => 'Fecal parasite detection kit',
            ],
            // Pet Food
            [
                'item_code' => 'FOOD-001',
                'category' => 'pet-food',
                'name' => 'Royal Canin Recovery',
                'brand' => 'Royal Canin',
                'batch_number' => 'RC2025-001',
                'current_stock' => 30,
                'min_stock' => 10,
                'max_stock' => 50,
                'unit_price' => 350.00,
                'expiry_date' => Carbon::now()->addMonths(12),
                'supplier' => 'PetFood Distributors',
                'location' => 'Food Storage',
                'description' => 'Recovery diet for cats and dogs',
            ],
            // --- Alert test items ---
            // Expired item
            [
                'item_code' => 'MED-006',
                'category' => 'medications',
                'name' => 'Doxycycline 100mg',
                'brand' => 'Generic',
                'batch_number' => 'DX2024-001',
                'current_stock' => 25,
                'min_stock' => 10,
                'max_stock' => 100,
                'unit_price' => 15.00,
                'expiry_date' => Carbon::now()->subDays(15),
                'supplier' => 'PetMeds Philippines',
                'location' => 'Shelf B2',
                'description' => 'Expired antibiotic — needs disposal',
            ],
            // Expired item (long overdue)
            [
                'item_code' => 'VAC-004',
                'category' => 'vaccines',
                'name' => 'Bordetella Vaccine',
                'brand' => 'Bronchi-Shield',
                'batch_number' => 'BS2024-001',
                'current_stock' => 10,
                'min_stock' => 5,
                'max_stock' => 40,
                'unit_price' => 600.00,
                'expiry_date' => Carbon::now()->subMonths(2),
                'supplier' => 'VetPharm Inc.',
                'location' => 'Cold Storage A2',
                'description' => 'Expired kennel cough vaccine',
            ],
            // Expiring in 7 days
            [
                'item_code' => 'MED-007',
                'category' => 'medications',
                'name' => 'Meloxicam 1.5mg/mL',
                'brand' => 'Metacam',
                'batch_number' => 'MC2025-001',
                'current_stock' => 12,
                'min_stock' => 5,
                'max_stock' => 30,
                'unit_price' => 420.00,
                'expiry_date' => Carbon::now()->addDays(7),
                'supplier' => 'PetMeds Philippines',
                'location' => 'Shelf B1',
                'description' => 'NSAID oral suspension — expiring very soon',
            ],
            // Expiring in 20 days
            [
                'item_code' => 'LAB-003',
                'category' => 'laboratory-supplies',
                'name' => 'Canine Parvovirus Test Kit',
                'brand' => 'BioNote',
                'batch_number' => 'BN2025-001',
                'current_stock' => 18,
                'min_stock' => 5,
                'max_stock' => 50,
                'unit_price' => 200.00,
                'expiry_date' => Carbon::now()->addDays(20),
                'supplier' => 'LabEquip Inc.',
                'location' => 'Lab Storage',
                'description' => 'Rapid test kit — expiring soon',
            ],
            // Out of stock
            [
                'item_code' => 'MED-008',
                'category' => 'medications',
                'name' => 'Ketoprofen 10mg/mL',
                'brand' => 'Ketofen',
                'batch_number' => 'KF2025-001',
                'current_stock' => 0,
                'min_stock' => 5,
                'max_stock' => 30,
                'unit_price' => 380.00,
                'expiry_date' => Carbon::now()->addMonths(6),
                'supplier' => 'PetMeds Philippines',
                'location' => 'Shelf B2',
                'description' => 'Injectable NSAID — out of stock',
            ],
            // Low stock
            [
                'item_code' => 'SUR-003',
                'category' => 'surgical-supplies',
                'name' => 'Disposable Scalpel Blades',
                'brand' => 'Swann-Morton',
                'batch_number' => 'SM2025-001',
                'current_stock' => 8,
                'min_stock' => 20,
                'max_stock' => 100,
                'unit_price' => 35.00,
                'expiry_date' => Carbon::now()->addMonths(18),
                'supplier' => 'MedSupply Co.',
                'location' => 'Surgical Cabinet',
                'description' => 'Scalpel blades #10 — running low',
            ],
            // Low stock
            [
                'item_code' => 'FOOD-002',
                'category' => 'pet-food',
                'name' => 'Hills Prescription Diet k/d',
                'brand' => 'Hills',
                'batch_number' => 'HL2025-001',
                'current_stock' => 3,
                'min_stock' => 8,
                'max_stock' => 30,
                'unit_price' => 450.00,
                'expiry_date' => Carbon::now()->addMonths(6),
                'supplier' => 'PetFood Distributors',
                'location' => 'Food Storage',
                'description' => 'Kidney care diet — low stock',
            ],
        ];

        foreach ($items as $itemData) {
            $category = $categories->get($itemData['category']);
            
            if ($category) {
                InventoryItem::firstOrCreate(
                    ['item_code' => $itemData['item_code']],
                    [
                        'user_id' => $userId,
                        'item_code' => $itemData['item_code'],
                        'inventory_category_id' => $category->id,
                        'name' => $itemData['name'],
                        'brand' => $itemData['brand'],
                        'batch_number' => $itemData['batch_number'],
                        'current_stock' => $itemData['current_stock'],
                        'min_stock' => $itemData['min_stock'],
                        'max_stock' => $itemData['max_stock'],
                        'unit_price' => $itemData['unit_price'],
                        'expiry_date' => $itemData['expiry_date'],
                        'supplier' => $itemData['supplier'],
                        'location' => $itemData['location'],
                        'description' => $itemData['description'],
                        'last_restocked_at' => Carbon::now(),
                    ]
                );
            }
        }
    }
}
